version: '3.8'

services:
  php:
    build: ./php
    volumes:
      - ./vanilla:/var/www/html/
    ports:
      - "8888:80"
    networks:
      - vanilla-network

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - vanilla-network

networks:
  vanilla-network:
